# Generated by Django 4.2.10 on 2024-02-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quakeApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_local', models.DateTimeField()),
                ('fecha_utc', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('profundidad', models.FloatField()),
                ('magnitud', models.FloatField()),
            ],
        ),
    ]
