# Generated by Django 4.2.10 on 2024-03-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quakeApi', '0002_sismo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
